services:
  product_api:
    build:
      context: .
      target: dev
      dockerfile: .docker/app/Dockerfile
    volumes:
      - ./:/app:delegated
    user: www-data
    restart: unless-stopped
    environment:
      APP_USER_ID: 1000
      APP_GROUP_ID: 1000
    tty: true
    depends_on:
      - products_mysql
    extra_hosts:
      - host.docker.internal:172.17.0.1

  products_mysql:
    image: mysql:8.0.32
    container_name: products_mysql
    volumes:
      - mysql_volumes:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
    ports:
      - "3306:3306"

  nginx:
    image: nginx:1.27.4-alpine
    ports:
      - 8080:80
    depends_on:
      - product_api
    volumes:
      - ./public:/app/public
      - .docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf

  greenmail:
    image: greenmail/standalone:2.1.3
    container_name: greenmail
    environment:
      GREENMAIL_OPTS: >
        -Dgreenmail.setup.test.all
        -Dgreenmail.hostname=0.0.0.0
        -Dgreenmail.users=alice:alice
volumes:
  mysql_volumes: ~
